//! The ways the client prints a stat that the trade catalog's one text per stat misses, taken
//! from Exiled Exchange 2's stat database (`data/stat-matchers-{en,ru}.tsv`, generated by
//! `packaging/data/generate_stat_matchers.py`; EE2 is MIT, see `data/NOTICE`): a negative roll
//! in words no `ClientStrings::negations` pair covers (`20% снижение требований к
//! характеристикам`), a 100% chance printed as a plain effect (`Blind Enemies on Hit`), a count
//! of one as a word (`You can apply one fewer Curse`). `catalog_match` falls back on them once
//! the catalog's own texts, the word pairs and grammatical number have all failed.

use std::collections::HashMap;
use std::sync::LazyLock;

use crate::catalog_match::without_break_spaces;

/// One printed form of a stat.
#[derive(Debug)]
pub struct StatForm {
    /// The form counts the stat the other way (`reduced` for the catalog's `increased`): the roll
    /// is negated.
    pub negated: bool,
    /// The value a form that prints no number stands for (a flag's 100, "one fewer"'s -1).
    pub value: Option<f64>,
    /// The trade stat ids it counts toward (`explicit.stat_2933846633`, ...).
    pub ids: Vec<&'static str>,
}

/// Printed forms, numbers as `#` and line breaks without the spaces around them, to the stats
/// they print.
pub type StatForms = HashMap<String, Vec<StatForm>>;

pub static EN: LazyLock<StatForms> =
    LazyLock::new(|| parse(include_str!("../data/stat-matchers-en.tsv")));
pub static RU: LazyLock<StatForms> =
    LazyLock::new(|| parse(include_str!("../data/stat-matchers-ru.tsv")));

/// The table's rows: form, `n` for a negated form, the value a numberless form stands for, the
/// comma-joined trade ids.
fn parse(table: &'static str) -> StatForms {
    let mut forms = StatForms::new();
    for row in table.lines() {
        let mut fields = row.split('\t');
        let (Some(form), Some(negated), Some(value), Some(ids)) =
            (fields.next(), fields.next(), fields.next(), fields.next())
        else {
            continue;
        };
        forms
            .entry(without_break_spaces(&form.replace("\\n", "\n")))
            .or_default()
            .push(StatForm {
                negated: negated == "n",
                value: value.parse().ok(),
                ids: ids.split(',').collect(),
            });
    }
    forms
}
